version: "3"

services:

  app:
    build: app/
    command: node app.js
#    network_mode: host
    expose:
      - "3000"
  nginx:
    build: nginx/
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"
    depends_on:
      - app
